this.game:=New GameObjectStructure(this.IdleGameManager,"Int",[224])
this.game.gameInstances:=New GameObjectStructure(this.game,"List",[176])
this.game.gameInstances._CollectionValType:="CrusadersGame.ChampionsGameInstance"
this.game.gameInstances.Controller:=New GameObjectStructure(this.game.gameInstances,"Int",[24])
this.game.gameInstances.Controller.userData:=New GameObjectStructure(this.game.gameInstances.Controller,"Int",[216])
this.game.gameInstances.Controller.userData.ActiveUserGameInstance:=New GameObjectStructure(this.game.gameInstances.Controller.userData,"Int",[756])
this.game.gameInstances.Controller.userData.ChestHandler:=New GameObjectStructure(this.game.gameInstances.Controller.userData,"Int",[32])
this.game.gameInstances.Controller.userData.ChestHandler.chestCounts:=New GameObjectStructure(this.game.gameInstances.Controller.userData.ChestHandler,"Dict",[24])
this.game.gameInstances.Controller.userData.ChestHandler.chestCounts._CollectionKeyType:="System.Int32"
this.game.gameInstances.Controller.userData.ChestHandler.chestCounts._CollectionValType:="System.Int32"
this.game.gameInstances.Controller.userData.HeroHandler:=New GameObjectStructure(this.game.gameInstances.Controller.userData,"Int",[16])
this.game.gameInstances.Controller.userData.HeroHandler.heroes:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler,"List",[24])
this.game.gameInstances.Controller.userData.HeroHandler.heroes._CollectionValType:="CrusadersGame.GameScreen.Hero"
this.game.gameInstances.Controller.userData.HeroHandler.heroes.def:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes,"Int",[24])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.def.name:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.def,"UTF-16",[56])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.def.ID:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.def,"Int",[16])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.def.SeatID:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.def,"Int",[520])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes,"Int",[184])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects,"Dict",[80])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName._CollectionKeyType:="System.Int32"
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName._CollectionValType:="System.Collections.Generic.List<CrusadersGame.Effects.EffectKey>"
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName,"List",[])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List._CollectionValType:="CrusadersGame.Effects.EffectKey"
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List,"Int",[16])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler.activeEffectHandlers:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler,"List",[344])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler.activeEffectHandlers._CollectionValType:="CrusadersGame.Effects.ActiveEffectKeyHandler"
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler.activeEffectHandlers.cardsInHand:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler.activeEffectHandlers,"List",[152])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler.activeEffectHandlers.cardsInHand._CollectionValType:="CrusadersGame.Effects.EllywickDeckOfManyThingsHandler.Card"
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler.activeEffectHandlers.cardsInHand.CardType:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler.activeEffectHandlers.cardsInHand,"Int",[64])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler.activeEffectHandlers.IsUltimateActive:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler.activeEffectHandlers,"Char",[284])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler.def:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler,"Int",[32])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler.def.Key:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.effects.effectKeysByHashedKeyName.List.parentEffectKeyHandler.def,"UTF-16",[24])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.upgradeHandler:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes,"Int",[824])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.upgradeHandler.upgradesByUpgradeId:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.upgradeHandler,"Dict",[32])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.upgradeHandler.upgradesByUpgradeId._CollectionKeyType:="System.Int32"
this.game.gameInstances.Controller.userData.HeroHandler.heroes.upgradeHandler.upgradesByUpgradeId._CollectionValType:="CrusadersGame.GameScreen.HeroUpgrade"
this.game.gameInstances.Controller.userData.HeroHandler.heroes.upgradeHandler.upgradesByUpgradeId.RequiredLevel:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes.upgradeHandler.upgradesByUpgradeId,"Int",[68])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.Benched:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes,"Char",[888])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.level:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes,"Int",[924])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.lastMaxHealth:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes,"Double",[984])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.overwhelm:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes,"Int",[868])
this.game.gameInstances.Controller.userData.HeroHandler.heroes.ActiveGameInstanceId_k__BackingField:=New GameObjectStructure(this.game.gameInstances.Controller.userData.HeroHandler.heroes,"Int",[852])
this.game.gameInstances.Controller.userData.ModronHandler:=New GameObjectStructure(this.game.gameInstances.Controller.userData,"Int",[216])
this.game.gameInstances.Controller.userData.ModronHandler.modronSaves:=New GameObjectStructure(this.game.gameInstances.Controller.userData.ModronHandler,"List",[32])
this.game.gameInstances.Controller.userData.ModronHandler.modronSaves._CollectionValType:="CrusadersGame.User.UserModronHandler.ModronCoreData"
this.game.gameInstances.Controller.userData.ModronHandler.modronSaves.FormationSaves:=New GameObjectStructure(this.game.gameInstances.Controller.userData.ModronHandler.modronSaves,"Dict",[24])
this.game.gameInstances.Controller.userData.ModronHandler.modronSaves.FormationSaves._CollectionKeyType:="System.Int32"
this.game.gameInstances.Controller.userData.ModronHandler.modronSaves.FormationSaves._CollectionValType:="System.Int32"
this.game.gameInstances.Controller.userData.ModronHandler.modronSaves.targetArea:=New GameObjectStructure(this.game.gameInstances.Controller.userData.ModronHandler.modronSaves,"Int",[84])
this.game.gameInstances.Controller.userData.ModronHandler.modronSaves.InstanceID:=New GameObjectStructure(this.game.gameInstances.Controller.userData.ModronHandler.modronSaves,"Int",[76])
this.game.gameInstances.Controller.userData.ModronHandler.modronSaves.TogglePreferences:=New GameObjectStructure(this.game.gameInstances.Controller.userData.ModronHandler.modronSaves,"Dict",[56])
this.game.gameInstances.Controller.userData.ModronHandler.modronSaves.TogglePreferences._CollectionKeyType:="System.Enum"
this.game.gameInstances.Controller.userData.ModronHandler.modronSaves.TogglePreferences._CollectionValType:="System.Boolean"
this.game.gameInstances.Controller.userData.FeatHandler:=New GameObjectStructure(this.game.gameInstances.Controller.userData,"Int",[184])
this.game.gameInstances.Controller.userData.FeatHandler.heroFeatSlots:=New GameObjectStructure(this.game.gameInstances.Controller.userData.FeatHandler,"Dict",[56])
this.game.gameInstances.Controller.userData.FeatHandler.heroFeatSlots._CollectionKeyType:="System.Int32"
this.game.gameInstances.Controller.userData.FeatHandler.heroFeatSlots._CollectionValType:="System.Collections.Generic.List<CrusadersGame.Defs.HeroFeatDef>"
this.game.gameInstances.Controller.userData.FeatHandler.heroFeatSlots.List:=New GameObjectStructure(this.game.gameInstances.Controller.userData.FeatHandler.heroFeatSlots,"List",[])
this.game.gameInstances.Controller.userData.FeatHandler.heroFeatSlots.List._CollectionValType:="CrusadersGame.Defs.HeroFeatDef"
this.game.gameInstances.Controller.userData.FeatHandler.heroFeatSlots.List.ID:=New GameObjectStructure(this.game.gameInstances.Controller.userData.FeatHandler.heroFeatSlots.List,"Int",[16])
this.game.gameInstances.Controller.userData.FeatHandler.heroFeatSlots.List.Name:=New GameObjectStructure(this.game.gameInstances.Controller.userData.FeatHandler.heroFeatSlots.List,"UTF-16",[24])
this.game.gameInstances.Controller.userData.SaveHandler:=New GameObjectStructure(this.game.gameInstances.Controller.userData,"Int",[296])
this.game.gameInstances.Controller.userData.SaveHandler.currentSave:=New GameObjectStructure(this.game.gameInstances.Controller.userData.SaveHandler,"Int",[24])
this.game.gameInstances.Controller.userData.SaveHandler.currentSave.Instances:=New GameObjectStructure(this.game.gameInstances.Controller.userData.SaveHandler.currentSave,"Dict",[40])
this.game.gameInstances.Controller.userData.SaveHandler.currentSave.Instances._CollectionKeyType:="System.Int32"
this.game.gameInstances.Controller.userData.SaveHandler.currentSave.Instances._CollectionValType:="CrusadersGame.User.UserSaveHandler.InstanceDetails"
this.game.gameInstances.Controller.userData.SaveHandler.lastUserDataSaveTime:=New GameObjectStructure(this.game.gameInstances.Controller.userData.SaveHandler,"Int64",[152])
this.game.gameInstances.Controller.userData.StatHandler:=New GameObjectStructure(this.game.gameInstances.Controller.userData,"Int",[48])
this.game.gameInstances.Controller.userData.StatHandler.BrivSteelbonesStacks:=New GameObjectStructure(this.game.gameInstances.Controller.userData.StatHandler,"Int",[856])
this.game.gameInstances.Controller.userData.StatHandler.BrivSprintStacks:=New GameObjectStructure(this.game.gameInstances.Controller.userData.StatHandler,"Int",[860])
this.game.gameInstances.Controller.userData.StatHandler.Resets:=New GameObjectStructure(this.game.gameInstances.Controller.userData.StatHandler,"Int",[192])
this.game.gameInstances.Controller.userData.StatHandler.ServerStats:=New GameObjectStructure(this.game.gameInstances.Controller.userData.StatHandler,"Dict",[136])
this.game.gameInstances.Controller.userData.StatHandler.ServerStats._CollectionKeyType:="System.String"
this.game.gameInstances.Controller.userData.StatHandler.ServerStats._CollectionValType:="Engine.Numeric.Quad"
this.game.gameInstances.Controller.userData.inited:=New GameObjectStructure(this.game.gameInstances.Controller.userData,"Char",[736])
this.game.gameInstances.Controller.userData.redRubies:=New GameObjectStructure(this.game.gameInstances.Controller.userData,"Int",[700])
this.game.gameInstances.Controller.userData.ResetCurrencyHandler:=New GameObjectStructure(this.game.gameInstances.Controller.userData,"Int",[120])
this.game.gameInstances.Controller.userData.ResetCurrencyHandler.ResetCurrencyDefs:=New GameObjectStructure(this.game.gameInstances.Controller.userData.ResetCurrencyHandler,"List",[24])
this.game.gameInstances.Controller.userData.ResetCurrencyHandler.ResetCurrencyDefs._CollectionValType:="CrusadersGame.Defs.ResetCurrencyDef"
this.game.gameInstances.Controller.userData.ResetCurrencyHandler.ResetCurrencyDefs.CurrentAmount:=New GameObjectStructure(this.game.gameInstances.Controller.userData.ResetCurrencyHandler.ResetCurrencyDefs,"Double",[112])
this.game.gameInstances.Controller.userData.ResetCurrencyHandler.ResetCurrencyDefs.ID:=New GameObjectStructure(this.game.gameInstances.Controller.userData.ResetCurrencyHandler.ResetCurrencyDefs,"Int",[16])
this.game.gameInstances.Controller.area:=New GameObjectStructure(this.game.gameInstances.Controller,"Int",[24])
this.game.gameInstances.Controller.area.Active:=New GameObjectStructure(this.game.gameInstances.Controller.area,"Char",[484])
this.game.gameInstances.Controller.areaTransitioner:=New GameObjectStructure(this.game.gameInstances.Controller,"Int",[64])
this.game.gameInstances.Controller.areaTransitioner.IsTransitioning_k__BackingField:=New GameObjectStructure(this.game.gameInstances.Controller.areaTransitioner,"Char",[56])
this.game.gameInstances.Controller.areaTransitioner.transitionDirection:=New GameObjectStructure(this.game.gameInstances.Controller.areaTransitioner,"Int",[60])
this.game.gameInstances.Controller.areaSkipHandler:=New GameObjectStructure(this.game.gameInstances.Controller,"Int",[144])
this.game.gameInstances.Controller.areaSkipHandler.skipStacks:=New GameObjectStructure(this.game.gameInstances.Controller.areaSkipHandler,"Stack",[24])
this.game.gameInstances.Controller.areaSkipHandler.skipStacks._CollectionValType:="System.Collections.Generic.Queue<CrusadersGame.GameScreen.AreaSkipHandler.SkipStack>"
this.game.gameInstances.Controller.areaSkipHandler.skipStacks.Queue:=New GameObjectStructure(this.game.gameInstances.Controller.areaSkipHandler.skipStacks,"Queue",[])
this.game.gameInstances.Controller.areaSkipHandler.skipStacks.Queue._CollectionValType:="CrusadersGame.GameScreen.AreaSkipHandler.SkipStack"
this.game.gameInstances.Controller.formation:=New GameObjectStructure(this.game.gameInstances.Controller,"Int",[40])
this.game.gameInstances.Controller.formation.slots:=New GameObjectStructure(this.game.gameInstances.Controller.formation,"List",[40])
this.game.gameInstances.Controller.formation.slots._CollectionValType:="CrusadersGame.GameScreen.FormationSlot"
this.game.gameInstances.Controller.formation.slots.hero:=New GameObjectStructure(this.game.gameInstances.Controller.formation.slots,"Int",[40])
this.game.gameInstances.Controller.formation.slots.hero.def:=New GameObjectStructure(this.game.gameInstances.Controller.formation.slots.hero,"Int",[24])
this.game.gameInstances.Controller.formation.slots.hero.def.ID:=New GameObjectStructure(this.game.gameInstances.Controller.formation.slots.hero.def,"Int",[16])
this.game.gameInstances.Controller.formation.slots.slotDef:=New GameObjectStructure(this.game.gameInstances.Controller.formation.slots,"Int",[272])
this.game.gameInstances.Controller.formation.slots.slotDef.Column:=New GameObjectStructure(this.game.gameInstances.Controller.formation.slots.slotDef,"Int",[48])
this.game.gameInstances.Controller.formation.transitionDir:=New GameObjectStructure(this.game.gameInstances.Controller.formation,"Int",[500])
this.game.gameInstances.Controller.formation.numAttackingMonstersReached:=New GameObjectStructure(this.game.gameInstances.Controller.formation,"Int",[512])
this.game.gameInstances.Controller.formation.numRangedAttackingMonsters:=New GameObjectStructure(this.game.gameInstances.Controller.formation,"Int",[516])
this.game.gameInstances.BuffHandler:=New GameObjectStructure(this.game.gameInstances,"Int",[104])
this.game.gameInstances.BuffHandler.activeBuffs:=New GameObjectStructure(this.game.gameInstances.BuffHandler,"List",[32])
this.game.gameInstances.BuffHandler.activeBuffs._CollectionValType:="CrusadersGame.Defs.BuffDef"
this.game.gameInstances.BuffHandler.activeBuffs.Name:=New GameObjectStructure(this.game.gameInstances.BuffHandler.activeBuffs,"UTF-16",[32])
this.game.gameInstances.ClickLevel:=New GameObjectStructure(this.game.gameInstances,"Int",[272])
this.game.gameInstances.ResetsSinceLastManual:=New GameObjectStructure(this.game.gameInstances,"Int",[252])
this.game.gameInstances.ResetHandler:=New GameObjectStructure(this.game.gameInstances,"Int",[72])
this.game.gameInstances.ResetHandler.resetting:=New GameObjectStructure(this.game.gameInstances.ResetHandler,"Char",[56])
this.game.gameInstances.PatronHandler:=New GameObjectStructure(this.game.gameInstances,"Int",[96])
this.game.gameInstances.PatronHandler.ActivePatron_k__BackingField:=New GameObjectStructure(this.game.gameInstances.PatronHandler,"Int",[32])
this.game.gameInstances.PatronHandler.ActivePatron_k__BackingField.ID:=New GameObjectStructure(this.game.gameInstances.PatronHandler.ActivePatron_k__BackingField,"Int",[16])
this.game.gameInstances.ActiveCampaignData:=New GameObjectStructure(this.game.gameInstances,"Int",[40])
this.game.gameInstances.ActiveCampaignData.currentObjective:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Int",[24])
this.game.gameInstances.ActiveCampaignData.currentObjective.ID:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData.currentObjective,"Int",[16])
this.game.gameInstances.ActiveCampaignData.currentArea:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Int",[40])
this.game.gameInstances.ActiveCampaignData.currentArea.QuestRemaining:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData.currentArea,"Int",[92])
this.game.gameInstances.ActiveCampaignData.currentArea.areaDef:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData.currentArea,"Int",[16])
this.game.gameInstances.ActiveCampaignData.currentArea.areaDef.MonsterDamageMultiplier:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData.currentArea.areaDef,"Double",[288])
this.game.gameInstances.ActiveCampaignData.currentArea.Health:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData.currentArea,"Quad",[104])
this.game.gameInstances.ActiveCampaignData.currentAreaID:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Int",[136])
this.game.gameInstances.ActiveCampaignData.highestAvailableAreaID:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Int",[144])
this.game.gameInstances.ActiveCampaignData.currentRules:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Int",[32])
this.game.gameInstances.ActiveCampaignData.currentRules.MonsterDamageModifier:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData.currentRules,"Double",[944])
this.game.gameInstances.ActiveCampaignData.currentRules.monsterbaseStats:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData.currentRules,"Int",[224])
this.game.gameInstances.ActiveCampaignData.currentRules.monsterbaseStats.BaseDPS:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData.currentRules.monsterbaseStats,"Double",[88])
this.game.gameInstances.ActiveCampaignData.currentRules.monsterbaseStats.DPSGrowthRateCurve:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData.currentRules.monsterbaseStats,"Dict",[24])
this.game.gameInstances.ActiveCampaignData.currentRules.monsterbaseStats.DPSGrowthRateCurve._CollectionKeyType:="System.Int32"
this.game.gameInstances.ActiveCampaignData.currentRules.monsterbaseStats.DPSGrowthRateCurve._CollectionValType:="Engine.Numeric.Quad"
this.game.gameInstances.ActiveCampaignData.minUltDPS:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Double",[552])
this.game.gameInstances.ActiveCampaignData.ultBasedOnDPS:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Char",[536])
this.game.gameInstances.ActiveCampaignData.highestHitDamage:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Quad",[464])
this.game.gameInstances.ActiveCampaignData.highestHitCooldown:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Double",[488])
this.game.gameInstances.ActiveCampaignData.ultFalloffExponent2:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Double",[560])
this.game.gameInstances.ActiveCampaignData.timeSinceHighestHit:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Double",[480])
this.game.gameInstances.ActiveCampaignData.ultFalloffDelay:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Double",[568])
this.game.gameInstances.ActiveCampaignData.ultFalloffPeriod:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Double",[576])
this.game.gameInstances.ActiveCampaignData.ultFalloffPeriodMod:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Double",[584])
this.game.gameInstances.ActiveCampaignData.adventureDef:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData,"Int",[16])
this.game.gameInstances.ActiveCampaignData.adventureDef._campaignDef:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData.adventureDef,"Int",[32])
this.game.gameInstances.ActiveCampaignData.adventureDef._campaignDef.ResetCurrencyID:=New GameObjectStructure(this.game.gameInstances.ActiveCampaignData.adventureDef._campaignDef,"Int",[192])
this.game.gameInstances.FormationSaveHandler:=New GameObjectStructure(this.game.gameInstances,"Int",[112])
this.game.gameInstances.FormationSaveHandler.formationCampaignID:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler,"Int",[136])
this.game.gameInstances.FormationSaveHandler.formationSavesV2:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler,"List",[56])
this.game.gameInstances.FormationSaveHandler.formationSavesV2._CollectionValType:="CrusadersGame.Defs.FormationSaveV2Def"
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Favorite:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler.formationSavesV2,"Int",[72])
this.game.gameInstances.FormationSaveHandler.formationSavesV2.SaveID:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler.formationSavesV2,"Int",[64])
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Formation:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler.formationSavesV2,"List",[24])
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Formation._CollectionValType:="System.Int32"
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Specializations:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler.formationSavesV2,"Dict",[40])
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Specializations._CollectionKeyType:="System.Int32"
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Specializations._CollectionValType:="System.Collections.Generic.List<System.Int32>"
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Specializations.List:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler.formationSavesV2.Specializations,"List",[])
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Specializations.List._CollectionValType:="System.Int32"
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Familiars:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler.formationSavesV2,"Dict",[32])
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Familiars._CollectionKeyType:="System.String"
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Familiars._CollectionValType:="System.Collections.Generic.List<System.Int32>"
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Familiars.List:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler.formationSavesV2.Familiars,"List",[])
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Familiars.List._CollectionValType:="System.Int32"
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Feats:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler.formationSavesV2,"Dict",[48])
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Feats._CollectionKeyType:="System.Int32"
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Feats._CollectionValType:="System.Collections.Generic.List<System.Int32>"
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Feats.List:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler.formationSavesV2.Feats,"List",[])
this.game.gameInstances.FormationSaveHandler.formationSavesV2.Feats.List._CollectionValType:="System.Int32"
this.game.gameInstances.FormationSaveHandler.mostRecentFormation:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler,"Int",[72])
this.game.gameInstances.FormationSaveHandler.mostRecentFormation.Favorite:=New GameObjectStructure(this.game.gameInstances.FormationSaveHandler.mostRecentFormation,"Int",[72])
this.game.gameInstances.OfflineHandler:=New GameObjectStructure(this.game.gameInstances,"Int",[32])
this.game.gameInstances.OfflineHandler.OfflineTimeRequested_k__BackingField:=New GameObjectStructure(this.game.gameInstances.OfflineHandler,"Int",[252])
this.game.gameInstances.OfflineHandler.CurrentStopReason_k__BackingField:=New GameObjectStructure(this.game.gameInstances.OfflineHandler,"Int",[268])
this.game.gameInstances.OfflineHandler.CurrentState_k__BackingField:=New GameObjectStructure(this.game.gameInstances.OfflineHandler,"Int",[240])
this.game.gameInstances.Screen:=New GameObjectStructure(this.game.gameInstances,"Int",[16])
this.game.gameInstances.Screen.uiController:=New GameObjectStructure(this.game.gameInstances.Screen,"Int",[976])
this.game.gameInstances.Screen.uiController.topBar:=New GameObjectStructure(this.game.gameInstances.Screen.uiController,"Int",[24])
this.game.gameInstances.Screen.uiController.topBar.objectiveProgressBox:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.topBar,"Int",[872])
this.game.gameInstances.Screen.uiController.topBar.objectiveProgressBox.areaBar:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.topBar.objectiveProgressBox,"Int",[936])
this.game.gameInstances.Screen.uiController.topBar.objectiveProgressBox.areaBar.autoProgressButton:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.topBar.objectiveProgressBox.areaBar,"Int",[880])
this.game.gameInstances.Screen.uiController.topBar.objectiveProgressBox.areaBar.autoProgressButton.toggled:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.topBar.objectiveProgressBox.areaBar.autoProgressButton,"Char",[1005])
this.game.gameInstances.Screen.uiController.bottomBar:=New GameObjectStructure(this.game.gameInstances.Screen.uiController,"Int",[32])
this.game.gameInstances.Screen.uiController.bottomBar.heroPanel:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.bottomBar,"Int",[912])
this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.activeBoxes:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.bottomBar.heroPanel,"HashSet",[960])
this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.activeBoxes._CollectionKeyType:="CrusadersGame.GameScreen.UIComponents.BottomBar.HeroBox"
this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.activeBoxes.hero:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.activeBoxes,"Int",[992])
this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.activeBoxes.hero.def:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.activeBoxes.hero,"Int",[24])
this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.activeBoxes.hero.def.ID:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.activeBoxes.hero.def,"Int",[16])
this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.activeBoxes.lastGold:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.activeBoxes,"Quad",[1128])
this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.clickDamageBox:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.bottomBar.heroPanel,"Int",[952])
this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.clickDamageBox.maxLevelUpAllowed:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.clickDamageBox,"Int",[988])
this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.clickDamageBox.levelUpAmount:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.bottomBar.heroPanel.clickDamageBox,"Int",[984])
this.game.gameInstances.Screen.uiController.ultimatesBar:=New GameObjectStructure(this.game.gameInstances.Screen.uiController,"Int",[40])
this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.ultimatesBar,"List",[936])
this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems._CollectionValType:="CrusadersGame.GameScreen.UIComponents.UltimatesBar.UltimatesBarItem"
this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems.hero:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems,"Int",[928])
this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems.hero.def:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems.hero,"Int",[24])
this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems.hero.def.ID:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems.hero.def,"Int",[16])
this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems.ultimateAttack:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems,"Int",[936])
this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems.ultimateAttack.internalCooldownTimer:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems.ultimateAttack,"Float",[184])
this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems.ultimateAttack.Queued:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems.ultimateAttack,"Char",[189])
this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems.Hotkey:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.ultimatesBar.ultimateItems,"Int",[956])
this.game.gameInstances.Screen.uiController.notificationManager:=New GameObjectStructure(this.game.gameInstances.Screen.uiController,"Int",[104])
this.game.gameInstances.Screen.uiController.notificationManager.notificationDisplay:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.notificationManager,"Int",[24])
this.game.gameInstances.Screen.uiController.notificationManager.notificationDisplay.welcomeBackNotification:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.notificationManager.notificationDisplay,"Int",[856])
this.game.gameInstances.Screen.uiController.notificationManager.notificationDisplay.welcomeBackNotification.Active:=New GameObjectStructure(this.game.gameInstances.Screen.uiController.notificationManager.notificationDisplay.welcomeBackNotification,"Char",[1169])
this.game.gameInstances.isDirty:=New GameObjectStructure(this.game.gameInstances,"Char",[276])
this.game.gameInstances.StatHandler:=New GameObjectStructure(this.game.gameInstances,"Int",[80])
this.game.gameInstances.StatHandler.ServerStats:=New GameObjectStructure(this.game.gameInstances.StatHandler,"Dict",[32])
this.game.gameInstances.StatHandler.ServerStats._CollectionKeyType:="System.String"
this.game.gameInstances.StatHandler.ServerStats._CollectionValType:="Engine.Numeric.Quad"
this.game.gameInstances.areaTransitionTimeScaleMultiplier:=New GameObjectStructure(this.game.gameInstances,"Float",[364])
this.game.gameInstances.InstanceUserData_k__BackingField:=New GameObjectStructure(this.game.gameInstances,"Int",[192])
this.game.gameInstances.InstanceUserData_k__BackingField.InstanceId:=New GameObjectStructure(this.game.gameInstances.InstanceUserData_k__BackingField,"Int",[320])
this.game.gameStarted:=New GameObjectStructure(this.game,"Char",[256])
this.game.gameUser:=New GameObjectStructure(this.game,"Int",[168])
this.game.gameUser.Loaded:=New GameObjectStructure(this.game.gameUser,"Char",[92])
this.game.loadingScreen:=New GameObjectStructure(this.game,"Int",[88])
this.game.loadingScreen.splashScreen:=New GameObjectStructure(this.game.loadingScreen,"Int",[968])
this.game.loadingScreen.splashScreen.IsActive_k__BackingField:=New GameObjectStructure(this.game.loadingScreen.splashScreen,"Char",[72])
this.TimeScale:=New GameObjectStructure(this.IdleGameManager,"Float",[136])
